### ISSUE TITLE
Use hetzner-k3s for easy cluster creation

### ISSUE THREAD

**Issue by rene-mueller** [dyrector-io/dyrectorio#694]
It would be great when you implement [hetnzer-k3s](https://github.com/vitobotta/hetzner-k3s) for easy cluster creation.

**Comment by nandor-magyar** [comment]
If you can access hetzner-k3s using kubectl, you can deploy the agent to the cluster and use it as a deployment target. Note that provisioning raw infrastructure components clusters/VMs is out the scope of dyrector.io.

**Comment by rene-mueller** [comment]
@nandor-magyar hetzner-k3s will initialize and manage the cluster.

**Comment by polaroi8d** [comment]
Thank you for your feedback! Our main focus is on managing services on users' infrastructure rather than managing infrastructure itself. As of now, we don't have any plans in our roadmap to provide cluster management capabilities. 

As mentioned by @nandor-magyar, setting up dyrector.io's agent in your cluster is a straightforward process. You can easily do this through our Node screen, where you have the flexibility to switch between Kubernetes and Docker technologies. If you have more questions please reach us on Discord otherwise, I will close this ticket because this is not an issue.
